// Chinese names for game content. The game itself is English, so every table
// shows the English name too — a player who can't match what the wiki says to
// what their bag says is worse off than one reading English.

export const itemNames = {
  iron_sword: '鐵劍',
  worn_iron_sword: '磨損的鐵劍',
  notched_iron_sword: '缺口鐵劍',
  dagger: '匕首',
  goblin_sword: '哥布林短劍',
  small_sword: '小劍',
  spear: '長槍',
  morningstar: '晨星錘',
  greatclub: '巨棍',
  steel_longsword: '精鋼長劍',
  torch: '火把',
  worn_torch: '燒剩的火把',
  wooden_shield: '木盾',
  raven_shield: '渡鴉盾',
  leather_helmet: '皮革頭盔',
  iron_helmet: '鐵盔',
  plate_helmet: '板甲頭盔',
  leather_armor: '皮甲',
  chain_mail: '鎖子甲',
  wool_cape: '羊毛斗篷',
  cape_dye: '斗篷染料',
  cape_transfer_kit: '斗篷轉印組',
  breastplate: '胸甲',
  leather_pants: '皮革長褲',
  plate_greaves: '板甲脛甲',
  leather_boots: '皮靴',
  iron_boots: '鐵靴',
  plate_boots: '板甲戰靴',
  leather_gloves: '皮革手套',
  iron_gauntlets: '鐵護手',
  plate_gauntlets: '板甲護手',
  ring_of_protection: '防護戒指',
  gold_ring: '金戒指',
  silver_necklace: '銀項鍊',
  leather_belt: '皮革腰帶',
  coin_pile: '錢幣堆',
  healing_potion: '治療藥水',
  scroll_of_return: '回城捲軸',
  scroll_of_enchant_weapon: '武器強化捲軸',
  scroll_of_enchant_armor: '防具強化捲軸',
  whetstone_oil: '磨刀油',
  scroll_of_party_summon: '隊伍召集捲軸',
  phoenix_talisman: '鳳凰護符',
  table: '桌子',
  stone_hearth: '石造壁爐',
  rustic_bed: '樸素木床',
  mandolin: '曼陀林',
  worn_mandolin: '磨損的曼陀林',
  fishing_rod: '釣竿',
  raw_minnow: '生鰷魚',
  raw_perch: '生鱸魚',
  raw_trout: '生鱒魚',
  river_salmon: '河鮭',
  golden_sturgeon: '黃金鱘',
  old_boot: '破舊靴子',
  clump_of_kelp: '海帶團',
  message_in_a_bottle: '瓶中信',
  sunken_coin_pouch: '沉沒的錢袋',
  apple: '蘋果',
  bread: '麵包',
  cheese: '起司',
  jerky: '肉乾',
  lembas_wafer: '蘭巴斯行路麵包',
  grilled_minnow: '烤鰷魚',
  grilled_perch: '烤鱸魚',
  grilled_trout: '烤鱒魚',
  grilled_salmon: '烤鮭魚',
  grilled_sturgeon: '烤鱘魚',
  campfire_kit: '營火組',
  tip_hat: '賣藝帽',
  greater_healing_potion: '高級治療藥水',
  celestial_timekeeper: '天文懷錶',
  crypt_key_5: '古墓鑰匙(5 層)',
  orc_key_5: '獸人巢穴鑰匙(5 層)',
  orc_key_10: '獸人巢穴鑰匙(10 層)',
  ogre_key_5: '食人魔要塞鑰匙(5 層)',
  ogre_key_10: '食人魔要塞鑰匙(10 層)',
  ogre_key_15: '食人魔要塞鑰匙(15 層)',
};

export const itemDescriptions = {
  iron_sword: '堅固的鐵製長劍。',
  worn_iron_sword: '用了很久的鐵製長劍。商人不會收購。',
  notched_iron_sword: '半獸人配發的制式武器 —— 刃口有缺角,也沒有鑄造印記。砍起來一樣,但賣價低很多。',
  dagger: '小巧但鋒利的匕首。',
  goblin_sword: '哥布林與獸人愛用的粗製短刃。',
  small_sword: '為小型戰士打造的緊湊粗刃。',
  spear: '木柄鐵尖的長槍。',
  morningstar: '皮革纏柄的釘刺鐵頭錘。笨重粗糙,但沒有刃口需要保養。',
  greatclub: '釘滿鐵刺的橡木棍棒。太重了,只有食人魔這種體型才揮得順手。',
  steel_longsword: '以回火鋼鍛造的長劍,握柄纏有環紋,劍柄配有輪形配重。鋼製鋒刃比鐵劍更耐用持久。',
  torch: '搖曳的木製火把。',
  worn_torch: '燒到一半的短火把。商人不會收購。',
  wooden_shield: '圓形木盾。',
  raven_shield: '繪有黑渡鴉紋章的圓形木盾。',
  leather_helmet: '簡單的皮革頭盔。',
  iron_helmet: '護住整個頭部的厚重鐵盔。',
  plate_helmet: '附面罩、包覆整個頭部的鋼製密閉盔。',
  leather_armor: '以皮帶與扣環交叉固定的柔韌皮製胸甲。',
  chain_mail: '互扣金屬環構成的護甲。',
  wool_cape: '厚重的羊毛斗篷,披在肩頭,行走時會隨風擺盪拖曳。',
  cape_dye: '一瓶塞著瓶塞的顏料。裝備斗篷時使用,可以把布料染成你選的顏色。',
  cape_transfer_kit: '一張蠟紙與一罐定色劑。裝備斗篷時使用,可以把自己的圖片印上布料。',
  breastplate: '拋光鋼製胸甲,除了最精準的一擊之外都能擋下。',
  leather_pants: '耐用的皮革護腿。',
  plate_greaves: '護住雙腿的分節鋼製脛甲。',
  leather_boots: '行走無聲的堅固皮靴。',
  iron_boots: '厚重的鐵靴。',
  plate_boots: '層疊鋼板護住雙足與小腿。',
  leather_gloves: '抓握穩固的柔韌皮手套。',
  iron_gauntlets: '護住手與手腕的厚重鐵護手。',
  plate_gauntlets: '包覆手與手腕的分節鋼製護手。',
  ring_of_protection: '鑲有十字盾紋章的銀戒,能擋開攻擊。',
  gold_ring: '樸素的金戒指。',
  silver_necklace: '細緻的銀鍊,墜著一枚豐收徽章。',
  leather_belt: '寬版皮革腰帶。',
  coin_pile: '一小堆散落的銅幣。',
  healing_potion: '深紅色的藥劑,能癒合傷口、恢復活力。',
  scroll_of_return: '誦讀神祕符文,在一道光芒中回到城鎮。',
  scroll_of_enchant_weapon: '能磨利手中武器的符文 —— 但貪心地反覆誦讀可能會毀掉它。',
  scroll_of_enchant_armor: '能強化身上一件防具的符文 —— 但貪心地反覆誦讀可能會毀掉它。',
  whetstone_oil: '一瓶用來養磨刀石的濃稠琥珀色油 —— 強化符文只吃得進上過油的裝備,誦讀一次就會耗掉一瓶。',
  scroll_of_party_summon: '誦讀符文可召集整支隊伍到身邊 —— 每個人都可以選擇響應或無視。',
  phoenix_talisman: '刻著烈焰鳳凰的石板。隨身攜帶,倒下時鳳凰便會甦醒 —— 你將在原地重新站起,護符隨即化為塵埃。',
  table: '堅固的木桌。',
  stone_hearth: '一座刻有盾徽的古老石造壁爐,直通天花板。',
  rustic_bed: '一張鋪著羊毛毯的簡樸木製單人床。',
  mandolin: '圓背鑲金琴格的曼陀林。用 /play_music 即可彈奏一曲。',
  worn_mandolin: '旅途中磨損、音色依舊純正的曼陀林。用 /play_music 即可彈奏一曲。商人不會收購。',
  fishing_rod: '馬鬃線的柔韌木釣竿。對著水面拋竿即可釣魚。',
  raw_minnow: '銀色小魚,勉強一口的份量。',
  raw_perch: '帶條紋的河鱸,還算好吃。',
  raw_trout: '有斑點的鱒魚,釣客敬重的對象。',
  river_salmon: '強壯的銀色鮭魚,值得驕傲的一尾。',
  golden_sturgeon: '比王國還古老的河中巨獸,骨板閃著鎚金般的光澤。',
  old_boot: '泡水的皮靴。有人今天過得比你更慘。',
  clump_of_kelp: '從水底撈起的黏滑海草。',
  message_in_a_bottle: '密封瓶裡有張紙條。收藏家或許願意出點錢。',
  sunken_coin_pouch: '沉入水底的錢袋,裡面還剩幾枚錢幣。',
  apple: '清脆的紅蘋果。',
  bread: '剛出爐的麵包。',
  cheese: '一塊硬起司,在路上也放得住。',
  jerky: '鹽漬肉乾,份量紮實又好攜帶。',
  lembas_wafer: '以葉子包裹的精靈行路麵包。薄薄一片就能撐過一整天的行軍。',
  grilled_minnow: '整條在營火上烤到酥脆的小魚。',
  grilled_perch: '烤到肉質鬆軟的條紋鱸魚。',
  grilled_trout: '帶著煙燻味的斑點鱒魚。',
  grilled_salmon: '在明火上煎過的鮭魚排。',
  grilled_sturgeon: '在餘燼上烘烤的鱘魚上等部位。',
  campfire_kit: '打包好的柴薪與火種,可燃燒十分鐘。',
  tip_hat: '一頂風霜的羽飾帽。表演前放下,聽眾就會把錢幣丟進去。再用一次可以收起來。',
  greater_healing_potion: '雙重釀製的深紅藥劑 —— 比一般治療藥水更濃稠、更厚重,藥效也強上一倍。',
  celestial_timekeeper: '一只黃銅打造的星盤懷錶,錶面追蹤日月運行。隨身攜帶,天色小工具旁便會顯示時辰與日期。',
  crypt_key_5: '一把鏽蝕的鐵鑰匙。可以打開古墓第 5 層的封鎖樓梯間,以及該地城的寶箱。',
  orc_key_5: '獸人手工打造的粗糙青銅鑰匙。可以打開獸人巢穴第 5 層的封鎖樓梯間。',
  orc_key_10: '刻著缺口的粗糙青銅鑰匙。可以打開獸人巢穴第 10 層的封鎖樓梯間,以及該地城的寶箱。',
  ogre_key_5: '沉重的黑鐵鑰匙。可以打開食人魔要塞第 5 層的封鎖樓梯間。',
  ogre_key_10: '鑰匙柄鑄有環形紋飾的沉重黑鐵鑰匙。可以打開食人魔要塞第 10 層的封鎖樓梯間。',
  ogre_key_15: '鑰匙柄鑄有王冠紋飾的沉重黑鐵鑰匙。可以打開食人魔要塞第 15 層的封鎖樓梯間,以及該地城的寶箱。',
};

export const monsterNames = {
  scp939: '潛行者',
  kobold: '狗頭人',
  goblin: '哥布林',
  orc: '獸人',
  orc_female: '女獸人',
  orc_boss: '獸人督軍',
  goblin_boss: '哥布林酋長',
  hobgoblin: '半獸人',
  gnoll: '豺狼人',
  bugbear: '大鬼怪',
  ogre: '食人魔',
  troll: '巨魔',
  ogre_boss: '食人魔督軍',
  stone_golem: '石魔像',
  cyclop: '獨眼巨人',
  lizardfolk: '蜥蜴人',
};

export const debuffNames = {
  bleed: '流血',
  food_poisoning: '食物中毒',
  wet: '濕透',
};

export const dungeonNames = {
  old_crypt: '古墓',
  orc_warrens: '獸人巢穴',
  ogre_stronghold: '食人魔要塞',
};

export const categoryNames = {
  weapon: '武器',
  armor: '防具',
  accessory: '飾品',
  food: '食物',
  fish: '生魚',
  junk: '雜物',
  coin_catch: '釣獲錢財',
  currency: '貨幣',
  healing_potion: '治療藥水',
  return_scroll: '回城捲軸',
  enchant_scroll: '強化捲軸',
  enchant_armor_scroll: '防具強化捲軸',
  party_summon_scroll: '召集捲軸',
  instrument: '樂器',
  furniture: '家具',
  fishing_rod: '釣具',
  campfire_kit: '營火',
  tip_hat: '賣藝帽',
  cape_dye: '斗篷染料',
  cape_texture: '斗篷印花',
  phoenix_talisman: '鳳凰護符',
  reagent: '藥劑材料',
  timekeeper: '計時器',
  dungeon_key: '地城鑰匙',
};

export const slotNames = {
  head: '頭部',
  main_hand: '主手',
  off_hand: '副手',
  chest: '身體',
  hands: '手部',
  pants: '腿部',
  boots: '腳部',
  belt: '腰帶',
  neck: '頸部',
  ring: '戒指',
  ear: '耳環',
  back: '背部',
};

export const materialNames = {
  metal: '金屬',
  wood: '木製',
  leather: '皮革',
  flesh: '血肉',
  cloth: '布料',
  stone: '石製',
};

export const behaviorNames = {
  brave: '主動攻擊',
  timid: '受攻擊才反擊',
};

export const mapKindNames = {
  continent: '大陸',
  capital: '首都',
  city: '城市',
  town: '城鎮',
  sea: '海域',
  island: '島嶼',
};

export const itemName = (id) => itemNames[id] ?? id;
export const monsterName = (id) => monsterNames[id] ?? id;
export const debuffName = (id) => debuffNames[id] ?? id;
